# This is a basic workflow to help you get started with Actions

name: Translate
id: ysnows/translate@main
author: 'open ai'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  translate:
    # The type of runner that the job will run on
    runs-on: mac

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: open ai
        uses: prompt
        env:
          temperature : 1
        with: 
          system: "act as an expert translator for zh-en translation, just return the translated result, don't explanation, the text to be translated is  : {{text|contextText}}" 
      # - name: read aloud
      #   uses: read aloud
      #   with: 
      #     system: "{{text|contextText}}" 

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
